version: "3"
services:
  service_registry:
    image: service-registry
    ports:
      - "8761:8761"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.5

  token_service:
    image: token-service
    ports:
      - "9099:9099"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.6
    depends_on:
      - service_registry
      - mongo_db

  mongo_db:
    image: 4130848d45a9
    ports:
      - "27017:27017"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1